services:
  main:
    container_name: ${PROJECT_NAME}
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        projectHomeDirpath: ./
        dockerImage: python:3.11-slim-bullseye
    ports:
      - "8000:8000"
